### ISSUE TITLE
multiHashing.randomx is not a function

### ISSUE THREAD

**Issue by ludwinator** [MoneroOcean/xmr-node-proxy#102]
1|proxy  | TypeError: multiHashing.randomx is not a function
1|proxy  |     at hash_func (/home/lud/xmr-node-proxy/lib/xmr.js:128:60)
1|proxy  |     at Object.processShare (/home/lud/xmr-node-proxy/lib/xmr.js:337:20)
1|proxy  |     at handleMinerData (/home/lud/xmr-node-proxy/proxy.js:1182:49)
1|proxy  |     at handleMessage (/home/lud/xmr-node-proxy/proxy.js:1411:13)
1|proxy  |     at Socket.<anonymous> (/home/lud/xmr-node-proxy/proxy.js:1469:25)
1|proxy  |     at emitOne (events.js:96:13)
1|proxy  |     at Socket.emit (events.js:188:7)
1|proxy  |     at readableAddChunk (_stream_readable.js:176:18)
1|proxy  |     at Socket.Readable.push (_stream_readable.js:134:10)
1|proxy  |     at TCP.onread (net.js:548:20)
1|proxy  | Worker 3314 died with code: 1, and signal: null

proxy is up-to-date

**Comment by MoneroOcean** [comment]
Try to do ```npm install``` or run ```update.sh``` script
