### ISSUE TITLE
Error on green field install

### ISSUE THREAD

**Issue by Akito01** [MoneroOcean/xmr-node-proxy#112]
Installing the XMR NP on Ubuntu 16.04 I get this error:
5515 verbose stack Error: cryptoforknote-util@6.0.0 install: `node-gyp rebuild`
5515 verbose stack Exit status 1
5515 verbose stack     at EventEmitter.<anonymous> (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
5515 verbose stack     at emitTwo (events.js:126:13)
5515 verbose stack     at EventEmitter.emit (events.js:214:7)
5515 verbose stack     at ChildProcess.<anonymous> (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
5515 verbose stack     at emitTwo (events.js:126:13)
5515 verbose stack     at ChildProcess.emit (events.js:214:7)
5515 verbose stack     at maybeClose (internal/child_process.js:925:16)
5515 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
5516 verbose pkgid cryptoforknote-util@6.0.0
5517 verbose cwd /home/nodeproxy/xmr-node-proxy
5518 verbose Linux 4.4.0-169-generic
5519 verbose argv "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/npm" "install"
5520 verbose node v8.11.3
5521 verbose npm  v5.6.0
5522 error code ELIFECYCLE
5523 error errno 1
5524 error cryptoforknote-util@6.0.0 install: `node-gyp rebuild`
5524 error Exit status 1
5525 error Failed at the cryptoforknote-util@6.0.0 install script.
5525 error This is probably not a problem with npm. There is likely additional logging output above.
5526 verbose exit [ 1, true ]

There's a log located at /home/nodeproxy/.npm/_logs/2019-12-03T10_49_00_612Z-debug.log but this is the only part where actual errors show up.
What's going on here?

**Comment by Akito01** [comment]
Additional info:
When running` "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"`

I'm presented with this error:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | linux | x64
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, unlink 'build'
gyp ERR! System Linux 4.4.0-169-generic
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
`

What to do?
