### ISSUE TITLE
Problems with installation 

### ISSUE THREAD

**Issue by xday3** [MoneroOcean/xmr-node-proxy#128]
Hi Dev, i try to install MoneroOcean/xmr-node-proxy script on my ubuntu 16 but I got this error:

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout v8.1.0
npm ERR! error: pathspec 'v8.1.0' did not match any file(s) known to git.
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-15T06_15_31_270Z-debug.log
============================
412 silly resolveWithNewModule request@2.88.2 checking installable status
413 silly pacote git manifest for cryptonight-hashing@git+https://github.com/MoneroOcean/node-cryptonight-hashing.git#v19.0.0 fetched in 1717ms
414 silly resolveWithNewModule cryptonight-hashing@19.0.0 checking installable status
415 silly fetchPackageMetaData error for cryptoforknote-util@git+https://github.com/MoneroOcean/node-cryptoforknote-util.git#v8.1.0 Command failed: /usr/bin/git checkout v8.1.0
415 silly fetchPackageMetaData error: pathspec 'v8.1.0' did not match any file(s) known to git.
416 silly saveTree xmr-node-proxy@0.18.0
416 silly saveTree +-- async@2.1.4
416 silly saveTree +-- bignum@0.12.5
416 silly saveTree +-- circular-buffer@1.0.2
416 silly saveTree +-- cryptonight-hashing@19.0.0
416 silly saveTree +-- debug@2.6.9
416 silly saveTree +-- express@4.14.0
416 silly saveTree +-- minimist@1.2.0
416 silly saveTree +-- moment@2.21.0
416 silly saveTree `-- request@2.88.2
417 verbose stack Error: Command failed: /usr/bin/git checkout v8.1.0
417 verbose stack error: pathspec 'v8.1.0' did not match any file(s) known to git.
417 verbose stack
417 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
417 verbose stack     at emitTwo (events.js:126:13)
417 verbose stack     at ChildProcess.emit (events.js:214:7)
417 verbose stack     at maybeClose (internal/child_process.js:925:16)
417 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
417 verbose stack     at emitOne (events.js:116:13)
417 verbose stack     at Socket.emit (events.js:211:7)
417 verbose stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
418 verbose cwd /root/xmr-node-proxy
419 verbose Linux 4.4.73-5-default
420 verbose argv "/root/.nvm/versions/node/v8.11.3/bin/node" "/root/.nvm/versions/node/v8.11.3/bin/npm" "install"
421 verbose node v8.11.3
422 verbose npm  v5.6.0
423 error code 1
424 error Command failed: /usr/bin/git checkout v8.1.0
424 error error: pathspec 'v8.1.0' did not match any file(s) known to git.
425 verbose exit [ 1, true ]

Let me know if you have any suggestion.

**Comment by MoneroOcean** [comment]
I rolled back problem change. Can you please try it again.

**Comment by xday3** [comment]
Yes, I tested and is working great now. Thank you very much!
