### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by yesilcimenahmet** [MoneroOcean/xmr-node-proxy#129]
```
 ./update.sh
Already up-to-date.

> cryptoforknote-util@8.1.1 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
In file included from ../src/cryptonote_core/cryptonote_basic.h:28:0,
                 from ../src/main.cc:8:
../src/ringct/rctTypes.h:39:37: fatal error: sodium/crypto_verify_32.h: No such file or directory
compilation terminated.
cryptoforknote.target.mk:114: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-176-generic
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@8.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptoforknote-util@8.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/./.npm/_logs/2020-07-21T05_19_08_347Z-debug.log
This is usually pm2 restart proxy, however, you can use pm2 list to check for your exact proxy command
```

**Comment by yesilcimenahmet** [comment]
Please help, proxy.js stopped after this event and is not running.

**Comment by yesilcimenahmet** [comment]
pm2 monit gives the following errors.

 ```
proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Debug/cryptonight-hashing.node                         x
x[ 1] proxy                          Mem:  44 MB    CPU: 48 %  online xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Release/cryptonight-hashing.node                   x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Release/cryptonight-hashing.node                       x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/default/cryptonight-hashing.node                 x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/compiled/8.11.3/linux/x64/cryptonight-hashing.node     x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/release/install-root/cryptonight-hashing.  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/debug/install-root/cryptonight-hashing.no  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/default/install-root/cryptonight-hashing.  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/lib/binding/node-v57-linux-x64/cryptonight-hashing.no  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/bindings/bindings.js:126:9)                                  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:1:99)                 x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Module._compile (module.js:652:30)                                                                                 x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Object.Module._extensions..js (module.js:663:10)                                                                   x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Module.load (module.js:565:32)                                                                                     x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at tryModuleLoad (module.js:505:12)                                                                                   x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Function.Module._load (module.js:497:3)                                                                            x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Module.require (module.js:596:17)                                                                                  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at Module.Hook._require.Module.require (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:     at require (internal/module.js:11:18)                                                                                 x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:   tries:                                                                                                                  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:    [ '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/cryptonight-hashing.node',                    x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Debug/cryptonight-hashing.node',              x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node',            x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Debug/cryptonight-hashing.node',                x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Debug/cryptonight-hashing.node',                    x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Release/cryptonight-hashing.node',              x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Release/cryptonight-hashing.node',                  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/default/cryptonight-hashing.node',            x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/compiled/8.11.3/linux/x64/cryptonight-hashing.node  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/release/install-root/cryptonight-hashi  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/debug/install-root/cryptonight-hashing  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/default/install-root/cryptonight-hashi  x
x                                                                     xx proxy > 2020-07-21 08:25:14:761 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/lib/binding/node-v57-linux-x64/cryptonight-hashing  x

```

**Comment by djfinch** [comment]
cryptoforknote dependencies was changed... you have to install 'libsodium-dev' via apt/yum/dnf/whatever...

**Comment by yesilcimenahmet** [comment]
can you help me ? can you write how to install?

**Comment by yesilcimenahmet** [comment]
sudo apt-get update -y

sudo apt-get install -y libsodium-dev

Thanks. I successfully installed. But the proxy still does not work. 


```
 proxy > 2020-07-21 09:41:29:154 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/release/install-root/cryptonight-hashi  x
x[ 1] proxy                          Mem:  32 MB    CPU:  0 %  online xx proxy > 2020-07-21 09:41:29:154 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/debug/install-root/cryptonight-hashing  x
x                                                                     xx proxy > 2020-07-21 09:41:29:154 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/default/install-root/cryptonight-hashi  x
x                                                                     xx proxy > 2020-07-21 09:41:29:154 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/lib/binding/node-v57-linux-x64/cryptonight-hashing  x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00: { Error: Could not locate the bindings file. Tried:                                                                       x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/cryptonight-hashing.node                         x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Debug/cryptonight-hashing.node                   x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node                 x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Debug/cryptonight-hashing.node                     x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Debug/cryptonight-hashing.node                         x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Release/cryptonight-hashing.node                   x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Release/cryptonight-hashing.node                       x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/default/cryptonight-hashing.node                 x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/compiled/8.11.3/linux/x64/cryptonight-hashing.node     x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/release/install-root/cryptonight-hashing.  x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/debug/install-root/cryptonight-hashing.no  x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/default/install-root/cryptonight-hashing.  x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:  → /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/lib/binding/node-v57-linux-x64/cryptonight-hashing.no  x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:     at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/bindings/bindings.js:126:9)                                  x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:1:99)                 x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:     at Module._compile (module.js:652:30)                                                                                 x
x                                                                     xx proxy > 2020-07-21 09:41:29:217 +03:00:     at Object.Module._extensions..js (module.js:663:10)                                                                   x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:     at Module.load (module.js:565:32)                                                                                     x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:     at tryModuleLoad (module.js:505:12)                                                                                   x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:     at Function.Module._load (module.js:497:3)                                                                            x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:     at Module.require (module.js:596:17)                                                                                  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:     at Module.Hook._require.Module.require (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/pm2/node_modules  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:     at require (internal/module.js:11:18)                                                                                 x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:   tries:                                                                                                                  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:    [ '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/cryptonight-hashing.node',                    x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Debug/cryptonight-hashing.node',              x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/Release/cryptonight-hashing.node',            x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Debug/cryptonight-hashing.node',                x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Debug/cryptonight-hashing.node',                    x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/out/Release/cryptonight-hashing.node',              x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/Release/cryptonight-hashing.node',                  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build/default/cryptonight-hashing.node',            x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/compiled/8.11.3/linux/x64/cryptonight-hashing.node  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/release/install-root/cryptonight-hashi  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/debug/install-root/cryptonight-hashing  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/addon-build/default/install-root/cryptonight-hashi  x
x                                                                     xx proxy > 2020-07-21 09:41:29:218 +03:00:      '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/lib/binding/node-v57-linux-x64/cryptonight-hashing 
```

**Comment by djfinch** [comment]
you have to run `npm i` or `yarn` once again. cryptoforknote util node binding is compiled from source and it fails previously because of missing libsodium-dev. to avoid any issues i strongly recommends you to remove whole `node_modules` folder and run `npm i` or `yarn` to install all modules from scratch...

**Comment by yesilcimenahmet** [comment]
that worked thank you very much!

**Comment by djfinch** [comment]
You're welcome... ;)
