### ISSUE TITLE
Failed to start Docker container

### ISSUE THREAD

**Issue by metal3d** [MoneroOcean/xmr-node-proxy#141]
Hello, 
Just updated, Docker image built and started. 

This happens:
```
 docker logs -f xnp2
Already up to date.
audited 138 packages in 1.607s

1 package is looking for funding
  run `npm fund` for details

found 18 vulnerabilities (4 low, 3 moderate, 10 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Proxy updated OK! Please go ahead and restart with the correct pm2 command
This is usually pm2 restart proxy, however, you can use pm2 list to check for your exact proxy command
Xmr-Node-Proxy (XNP) v0.21.2
Cluster master setting up 2 workers...
/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:9
const NBase                  = BigInt(Math.pow(2, 26));
                               ^

ReferenceError: BigInt is not defined
    at Object.<anonymous> (/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:9:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xmr-node-proxy/lib/xmr.js:2:22)
    at Module._compile (module.js:653:30)
Already up to date.
audited 138 packages in 1.668s

1 package is looking for funding
  run `npm fund` for details

found 18 vulnerabilities (4 low, 3 moderate, 10 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Proxy updated OK! Please go ahead and restart with the correct pm2 command
This is usually pm2 restart proxy, however, you can use pm2 list to check for your exact proxy command
Xmr-Node-Proxy (XNP) v0.21.2
Cluster master setting up 2 workers...
/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:9
const NBase                  = BigInt(Math.pow(2, 26));
                               ^

ReferenceError: BigInt is not defined
    at Object.<anonymous> (/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:9:32)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/xmr-node-proxy/lib/xmr.js:2:22)
    at Module._compile (module.js:653:30)
```

I'm on 60f839b4817e7e82ba134b4a6177fbb14bfe750c commit

**Comment by metal3d** [comment]
Maybe related to #139 because I don't see any changes in node version in the Dockerfile

**Comment by metal3d** [comment]
I made changes to use node 14, the problem is the same.
Can you please help me to fix this ?

**Comment by vacSQL** [comment]
Just remove the docker image and install it again 
Before you install it remove update.sh from the dockerfile
From 
CMD ./update.sh && node proxy.js
To 
CMD node proxy.js
It happened to me and I fix it like that

**Comment by metal3d** [comment]
Right, thanks.

And sorry for the delay !
