### ISSUE TITLE
error while trying to run deploy scriot with npm install of blake@4.1.1

### ISSUE THREAD

**Issue by littlAcen** [MoneroOcean/xmr-node-proxy#143]
this is what the logfile says:

3456 verbose stack Error: blake2@4.1.1 install: `node-gyp rebuild`
3456 verbose stack Exit status 1
3456 verbose stack     at EventEmitter.<anonymous> (/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3456 verbose stack     at EventEmitter.emit (events.js:375:28)
3456 verbose stack     at ChildProcess.<anonymous> (/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3456 verbose stack     at ChildProcess.emit (events.js:375:28)
3456 verbose stack     at maybeClose (internal/child_process.js:1055:16)
3456 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
3457 verbose pkgid blake2@4.1.1
3458 verbose cwd /home/nodeproxy/xmr-node-proxy
3459 verbose Linux 6.5.0-kali3-amd64
3460 verbose argv "/home/nodeproxy/.nvm/versions/node/v14.17.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v14.17.3/bin/npm" "install"
3461 verbose node v14.17.3
3462 verbose npm  v6.14.13
3463 error code ELIFECYCLE
3464 error errno 1
3465 error blake2@4.1.1 install: `node-gyp rebuild`
3465 error Exit status 1
3466 error Failed at the blake2@4.1.1 install script.
3466 error This is probably not a problem with npm. There is likely additional logging output above.
3467 verbose exit [ 1, true ]

**Comment by littlAcen** [comment]
npm install || exit 1

> blake2@4.1.1 install /home/nodeproxy/xmr-node-proxy/node_modules/blake2
> node-gyp rebuild

Traceback (most recent call last):
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 6.5.0-kali3-amd64
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v14.17.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v14.17.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/blake2
gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blake2@4.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blake2@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2023-11-30T18_52_20_986Z-debug.log
logout
