### ISSUE TITLE
Masari mining doesn't work

### ISSUE THREAD

**Issue by 7evenmikser** [MoneroOcean/xmr-node-proxy#22]
Hello, updated proxy, still works perfect with XMR but masari mining fails.
Here it is error log:
Error: Failed to parse block
    at Error (native)
    at BlockTemplate.nextBlob (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:84:23)
    at Miner.getJob (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:127:36)
    at handleMinerData (/home/nodeproxy/xmr-node-proxy/proxy.js:916:28)
    at handleMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:1092:13)
    at Socket.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:1150:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

**Comment by MoneroOcean** [comment]
And it should not work. Proxy is designed for Monero mining primarily and to switch to MSR mining it gets corresponding signal from the compatible pool. No option to add MSR mining via proxy config at this moment.

**Comment by 7evenmikser** [comment]
@MoneroOcean thanks for quick reply. I saw "Added masari support" connit and thought it should work. Any ETA for this?

**Comment by MoneroOcean** [comment]
Maybe week or so.

**Comment by 7evenmikser** [comment]
@MoneroOcean thanks a lot!

**Comment by MoneroOcean** [comment]
I added support for algo and blob_type to pool section of config.json in v0.1.4. For Masari it should be 

`
      "algo": "cryptonight/1",
      "blob_type": "cryptonote2",
`
