### ISSUE TITLE
Error while updating on RaspberryPi

### ISSUE THREAD

**Issue by KnoAll** [MoneroOcean/xmr-node-proxy#70]
getting this error when updating...
`/xmr-node-proxy $ ./update.sh
Already up-to-date.

> cryptonight-hashing@3.0.3 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp: Call to 'grep Intel /proc/cpuinfo >/dev/null && echo -DCPU_INTEL || (grep AMD /proc/cpuinfo >/dev/null && echo -DCPU_AMD)' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2018-10-02T21_16_32_171Z-debug.log
This is usually pm2 restart proxy, however, you can use pm2 list to check for your exact proxy command
`

**Comment by KnoAll** [comment]
hopefully my n00b status doesn't put me too over my skis here
in poking around maybe there is a missing string for ARM processors in node-cryptonight-hashing/binding.gyp

i dont even know if it is supported on ARM, but possibly should include something like this? 
|| (grep ARM /proc/cpuinfo >/dev/null && echo -DCPU_ARM)

**Comment by MoneroOcean** [comment]
Yeah, 'grep Intel /proc/cpuinfo >/dev/null && echo -DCPU_INTEL || (grep AMD /proc/cpuinfo >/dev/null && echo -DCPU_AMD)' misses clause for non Intel/AMD platforms. I hopefully fixed that. Could you please run update.sh again and confirm/deny.

**Comment by KnoAll** [comment]
Got another error...
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util/build'

> cryptonight-hashing@3.0.3 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp: Call to 'uname -a | grep "x86_64" >/dev/null && echo "xmrig/crypto/asm/cnv2_main_loop.S"' returned exit status 1 wh                                                                              ile in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_module                                                                              s/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/n                                                                              ode_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@3.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2018-10-03T14_38_59_265Z-debug.log

**Comment by MoneroOcean** [comment]
Yeah, forgot about this one. Please try to run update again.

**Comment by KnoAll** [comment]
That seems to have done it!

**Comment by djfinch** [comment]
I think this was not expected but this version of XNP works also on rPi2!!!

**Comment by djfinch** [comment]
I did a small inspect of cryptonight-hashing engine and saw armv7 strings everywhere so I thought it is worth to test it. It is! Awesome work. 14+hours of running without any # or connection issues. I'm running some other services there but I'm pretty sure that clean rPi2 can handle more than 300 miners without share validation throttling...
