### ISSUE TITLE
Minexmr.com compatibility

### ISSUE THREAD

**Issue by Niek** [MoneroOcean/xmr-node-proxy#80]
Are there any plans to add compatibility for Minexmr.com? Currently, it crashes with this error:

```javascript
Received new block template on undefined height with undefined target difficulty from pool.minexmr.com
/home/nodeproxy/xmr-node-proxy/proxy.js:841
    if (!blockTemplate.algo)      blockTemplate.algo = pool.coinFuncs.detectAlgo(pool.default_algo_set, 16 * parseInt(blockTemplate.blocktemplate_blob[0]) + parseInt(blockTemplate.blocktemplate_blob[1]));
                                                                                                                                                      ^

TypeError: Cannot read property '0' of undefined
    at handleNewBlockTemplate (/home/nodeproxy/xmr-node-proxy/proxy.js:841:151)
    at handlePoolMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:811:17)
    at Socket.socket.on (/home/nodeproxy/xmr-node-proxy/proxy.js:774:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
```

**Comment by bobbieltd** [comment]
minexmr is not nodejs-pool (Snipa) so it won’t work.
@MoneroOcean : just a flash in my thought, I think we can make xnp to work with non nodejs-pool. Just add one more mechanism to it (xmrig-proxy).

**Comment by bobbieltd** [comment]
Check pool :
1. If pool is nodejs-pool, proxy handle to reduce diff like original.
2. If pool is not nodejs-pool, proxy handle like xmrig proxy (I still don’t see any advantages of xmrig proxy besides switching pool - xmrig dev says so, too).

**Comment by ALLRiPPED** [comment]
implementations have already been made to cryptonote-nodejs-pool
 to fix this problem with xmr-node-proxy https://github.com/dvandal/cryptonote-nodejs-pool/pull/279/commits/fe6b656f9807101caaf55994994694bbce46218a
not sure why the same cannot be reverse engineered for the proxy.

**Comment by bobbieltd** [comment]
It minexmr’s admin need to add Dvandal’s codes into his pool to make xmr-node-proxy comptability. Not big deal with him if he wants.
