### ISSUE TITLE
Problems with new Fork Masari

### ISSUE THREAD

**Issue by Sevilla404** [MoneroOcean/xmr-node-proxy#85]
I update xmr-node-proxy to the latest version and i cant make work.!

proxy  | 2019-01-31 11:03 -06:00: Worker 9165 died with code: 1, and signal: null
1|proxy  | 2019-01-31 11:03 -06:00: Starting a new worker
1|proxy  | 2019-01-31 11:03 -06:00: Worker 9242 is online
1|proxy  | 2019-01-31 11:03 -06:00: Error: Failed to parse block
1|proxy  |     at BlockTemplate.nextBlob (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:155:23)
1|proxy  |     at Miner.getJob (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:198:36)
1|proxy  |     at handleMinerData (/home/nodeproxy/xmr-node-proxy/proxy.js:1097:28)
1|proxy  |     at handleMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:1389:13)
1|proxy  |     at Socket.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:1447:25)
1|proxy  |     at emitOne (events.js:116:13)
1|proxy  |     at Socket.emit (events.js:211:7)
1|proxy  |     at addChunk (_stream_readable.js:263:12)
1|proxy  |     at readableAddChunk (_stream_readable.js:246:13)
1|proxy  |     at Socket.Readable.push (_stream_readable.js:208:10)
1|proxy  | 2019-01-31 11:03 -06:00: Worker 9170 died with code: 1, and signal: null

using in my config.json
     "algo": [ "cn/half" ],
      "blob_type": "cryptonote",

  "coinSettings": {
    "xmr":{
      "minDiff": 3000,
      "maxDiff": 300000,
      "shareTargetTime": 30
    }

**Comment by 7evenmikser** [comment]
Try "blob_type": "cryptonote3"
