### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by 7evenmikser** [MoneroOcean/xmr-node-proxy#87]
Compilation of latest cryptoforknote-util stucks the process. Processor goes 100% and finally getting this error. 

make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util/build'
  CXX(target) Release/obj.target/cryptoforknote/src/main.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
cryptoforknote.target.mk:117: recipe for target 'Release/obj.target/cryptoforknote/src/main.o' failed
make: *** [Release/obj.target/cryptoforknote/src/main.o] Error 4
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-130-generic
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptoforknote-util
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptoforknote-util@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptoforknote-util@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nodeproxy/.npm/_logs/2019-02-13T12_51_55_836Z-debug.log

Temporary solution - copy/paste old version of cryptoforknote-util fron old build.

**Comment by 7evenmikser** [comment]
[2019-02-13T13_51_31_392Z-debug.log](https://github.com/MoneroOcean/xmr-node-proxy/files/2860591/2019-02-13T13_51_31_392Z-debug.log)

Tried to install it separately from your repository - same result. Attaching debug log.

**Comment by bobbieltd** [comment]
Add more swap. Compilation needs more memory than normal.
