### ISSUE TITLE
build error on clean install

### ISSUE THREAD

**Issue by NightHouse** [MoneroOcean/xmr-node-proxy#96]
While running install.sh I get:

SOLINK_MODULE(target) Release/obj.target/cryptonight-hashing.node
/usr/bin/ld: Release/obj.target/cryptonight-hashing/xmrig/crypto/asm/CryptonightR_template.o: relocation R_X86_64_PC32 against Symbol `CryptonightWOW_template_mainloop' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Ung▒ltiger Wert
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/cryptonight-hashing.node] Fehler 1
make: Verzeichnis ▒/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/build▒ wird verlassen
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.13.0-142-generic
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v8.11.3/bin/node" "/home/nodeproxy/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@9.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@9.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I can find 

relocation R_X86_64_PC32 against Symbol `CryptonightWOW_template_mainloop' can not be used when making a shared object; recompile with -fPIC

and I did an 

export CFLAGS="-fPIC"
export CXXFLAGS="$CFLAGS"

and rerun. Same error again.

After the run, there ist no directory  cryptonight-hashing  in  xmr-node-proxy/node_modules/

Any hints? What am I doing wrong?

**Comment by NightHouse** [comment]
Update:
I downloaded an Edubuntu 14.04 ISO and booted a LiveSystem from a 32 GB MemStick.

Same error!

**Comment by djfinch** [comment]
Is 14.04 really needed? It's quite old and build tools will be outdated, too. So it's maybe something with gcc (not sure which version is there).

**Comment by NightHouse** [comment]
Yes, I got it... 14.04 not working.

Did try with 16.04 LiveSystem and no errors.
